/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
/**
 *
 * @author aisyahzck
 */
public class pizza extends javax.swing.JFrame {

    int i, quantity;
    private double total1=0.0, total2=0.0;
    public double totalPizza1=0.0,totalPizza2=0.0, totalPizza3=0.0, totalPizza4=0.0, totalPizza5=0.0, totalPizza6=0.0;
    double sales, tax=0.12;
    String items, qty;
    
   //int[] choice = {1, 2, 3, 4, 5, 6};
   double[] price = {25.00, 26.00, 28.00};
    
    /**
     * Creates new form pizza
     */
    public pizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnBuy1 = new java.awt.Button();
        btnBuy2 = new java.awt.Button();
        btnBuy3 = new java.awt.Button();
        btnBuy4 = new java.awt.Button();
        btnBuy5 = new java.awt.Button();
        btnBuy6 = new java.awt.Button();
        btnReceipt = new java.awt.Button();
        btnClear = new java.awt.Button();
        btnTotal = new java.awt.Button();
        ItemFinalTotal = new javax.swing.JTextField();
        Qty1 = new javax.swing.JTextField();
        Price1 = new javax.swing.JTextField();
        ItemTotal = new javax.swing.JTextField();
        No1 = new javax.swing.JTextField();
        Item1 = new javax.swing.JTextField();
        No2 = new javax.swing.JTextField();
        Item2 = new javax.swing.JTextField();
        Price2 = new javax.swing.JTextField();
        Qty2 = new javax.swing.JTextField();
        No3 = new javax.swing.JTextField();
        Item3 = new javax.swing.JTextField();
        Price3 = new javax.swing.JTextField();
        Qty3 = new javax.swing.JTextField();
        No4 = new javax.swing.JTextField();
        Item4 = new javax.swing.JTextField();
        Price4 = new javax.swing.JTextField();
        Qty4 = new javax.swing.JTextField();
        No5 = new javax.swing.JTextField();
        Item5 = new javax.swing.JTextField();
        Price5 = new javax.swing.JTextField();
        Qty5 = new javax.swing.JTextField();
        No6 = new javax.swing.JTextField();
        Item6 = new javax.swing.JTextField();
        Price6 = new javax.swing.JTextField();
        Qty6 = new javax.swing.JTextField();
        Lbl1 = new java.awt.Label();
        Lbl2 = new java.awt.Label();
        Lbl3 = new java.awt.Label();
        Lbl4 = new java.awt.Label();
        Lbl5 = new java.awt.Label();
        Lbl6 = new java.awt.Label();
        LblPrice = new javax.swing.JLabel();
        LblItems = new javax.swing.JLabel();
        LblNo = new javax.swing.JLabel();
        LblQuantity = new javax.swing.JLabel();
        LblItems3 = new javax.swing.JLabel();
        LblItems2 = new javax.swing.JLabel();
        LblItems1 = new javax.swing.JLabel();
        jPhoto1 = new javax.swing.JLabel();
        jPhoto4 = new javax.swing.JLabel();
        jPhoto6 = new javax.swing.JLabel();
        jPhoto8 = new javax.swing.JLabel();
        jPhoto9 = new javax.swing.JLabel();
        jPhoto11 = new javax.swing.JLabel();
        JGif = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        JBackground = new javax.swing.JLabel();

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PIZZA YUM!");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 730));
        getContentPane().setLayout(null);

        btnBuy1.setBackground(new java.awt.Color(0, 204, 102));
        btnBuy1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuy1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy1.setLabel("RM26.00");
        btnBuy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy1);
        btnBuy1.setBounds(490, 370, 130, 50);

        btnBuy2.setBackground(new java.awt.Color(0, 204, 102));
        btnBuy2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuy2.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy2.setLabel("RM26.00");
        btnBuy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy2);
        btnBuy2.setBounds(790, 370, 130, 50);

        btnBuy3.setBackground(new java.awt.Color(0, 204, 102));
        btnBuy3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuy3.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy3.setLabel("RM28.00");
        btnBuy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy3);
        btnBuy3.setBounds(1100, 360, 130, 50);

        btnBuy4.setBackground(new java.awt.Color(0, 204, 102));
        btnBuy4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuy4.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy4.setLabel("RM28.00");
        btnBuy4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy4);
        btnBuy4.setBounds(490, 630, 130, 50);

        btnBuy5.setBackground(new java.awt.Color(0, 204, 102));
        btnBuy5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuy5.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy5.setLabel("RM25.00");
        btnBuy5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy5);
        btnBuy5.setBounds(810, 630, 130, 50);

        btnBuy6.setBackground(new java.awt.Color(0, 204, 102));
        btnBuy6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuy6.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy6.setLabel("RM28.00");
        btnBuy6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuy6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy6);
        btnBuy6.setBounds(1110, 630, 130, 50);

        btnReceipt.setBackground(new java.awt.Color(255, 0, 0));
        btnReceipt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnReceipt.setLabel("Print Receipt");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });
        getContentPane().add(btnReceipt);
        btnReceipt.setBounds(140, 640, 120, 40);

        btnClear.setBackground(new java.awt.Color(0, 204, 102));
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(240, 240, 240));
        btnClear.setLabel("Clear Order");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(80, 590, 110, 40);

        btnTotal.setBackground(new java.awt.Color(0, 204, 102));
        btnTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(240, 240, 240));
        btnTotal.setLabel("Total Price");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal);
        btnTotal.setBounds(210, 590, 110, 40);

        ItemFinalTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemFinalTotalActionPerformed(evt);
            }
        });
        getContentPane().add(ItemFinalTotal);
        ItemFinalTotal.setBounds(240, 520, 130, 30);

        Qty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qty1.setText("0");
        Qty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qty1ActionPerformed(evt);
            }
        });
        getContentPane().add(Qty1);
        Qty1.setBounds(330, 220, 40, 30);

        Price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price1ActionPerformed(evt);
            }
        });
        getContentPane().add(Price1);
        Price1.setBounds(240, 220, 80, 30);

        ItemTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemTotalActionPerformed(evt);
            }
        });
        getContentPane().add(ItemTotal);
        ItemTotal.setBounds(240, 480, 130, 30);

        No1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                No1MouseClicked(evt);
            }
        });
        No1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No1ActionPerformed(evt);
            }
        });
        getContentPane().add(No1);
        No1.setBounds(40, 220, 40, 30);

        Item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item1ActionPerformed(evt);
            }
        });
        getContentPane().add(Item1);
        Item1.setBounds(90, 220, 140, 30);
        getContentPane().add(No2);
        No2.setBounds(40, 260, 40, 30);
        getContentPane().add(Item2);
        Item2.setBounds(90, 260, 140, 30);
        getContentPane().add(Price2);
        Price2.setBounds(240, 260, 80, 30);

        Qty2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qty2.setText("0");
        Qty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qty2ActionPerformed(evt);
            }
        });
        getContentPane().add(Qty2);
        Qty2.setBounds(330, 260, 40, 30);

        No3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No3ActionPerformed(evt);
            }
        });
        getContentPane().add(No3);
        No3.setBounds(40, 300, 40, 30);
        getContentPane().add(Item3);
        Item3.setBounds(90, 300, 140, 30);
        getContentPane().add(Price3);
        Price3.setBounds(240, 300, 80, 30);

        Qty3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qty3.setText("0");
        Qty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qty3ActionPerformed(evt);
            }
        });
        getContentPane().add(Qty3);
        Qty3.setBounds(330, 300, 40, 30);
        getContentPane().add(No4);
        No4.setBounds(40, 340, 40, 30);
        getContentPane().add(Item4);
        Item4.setBounds(90, 340, 140, 30);
        getContentPane().add(Price4);
        Price4.setBounds(240, 340, 80, 30);

        Qty4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qty4.setText("0");
        Qty4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qty4ActionPerformed(evt);
            }
        });
        getContentPane().add(Qty4);
        Qty4.setBounds(330, 340, 40, 30);
        getContentPane().add(No5);
        No5.setBounds(40, 380, 40, 30);
        getContentPane().add(Item5);
        Item5.setBounds(90, 380, 140, 30);

        Price5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price5ActionPerformed(evt);
            }
        });
        getContentPane().add(Price5);
        Price5.setBounds(240, 380, 80, 30);

        Qty5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qty5.setText("0");
        getContentPane().add(Qty5);
        Qty5.setBounds(330, 380, 40, 30);

        No6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No6ActionPerformed(evt);
            }
        });
        getContentPane().add(No6);
        No6.setBounds(40, 420, 40, 30);

        Item6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item6ActionPerformed(evt);
            }
        });
        getContentPane().add(Item6);
        Item6.setBounds(90, 420, 140, 30);

        Price6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price6ActionPerformed(evt);
            }
        });
        getContentPane().add(Price6);
        Price6.setBounds(240, 420, 80, 30);

        Qty6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Qty6.setText("0");
        Qty6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qty6ActionPerformed(evt);
            }
        });
        getContentPane().add(Qty6);
        Qty6.setBounds(330, 420, 40, 30);

        Lbl1.setAlignment(java.awt.Label.CENTER);
        Lbl1.setBackground(new java.awt.Color(0, 204, 204));
        Lbl1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Lbl1.setForeground(new java.awt.Color(255, 255, 255));
        Lbl1.setText("Pepperoni Pizza");
        getContentPane().add(Lbl1);
        Lbl1.setBounds(480, 330, 150, 30);

        Lbl2.setAlignment(java.awt.Label.CENTER);
        Lbl2.setBackground(new java.awt.Color(0, 204, 204));
        Lbl2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Lbl2.setForeground(new java.awt.Color(255, 255, 255));
        Lbl2.setText("Aloha Pizza");
        getContentPane().add(Lbl2);
        Lbl2.setBounds(780, 330, 150, 30);

        Lbl3.setAlignment(java.awt.Label.CENTER);
        Lbl3.setBackground(new java.awt.Color(0, 204, 204));
        Lbl3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Lbl3.setForeground(new java.awt.Color(255, 255, 255));
        Lbl3.setText("Meaty Mushroom Pizza");
        getContentPane().add(Lbl3);
        Lbl3.setBounds(1080, 320, 180, 30);

        Lbl4.setAlignment(java.awt.Label.CENTER);
        Lbl4.setBackground(new java.awt.Color(0, 204, 204));
        Lbl4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Lbl4.setForeground(new java.awt.Color(255, 255, 255));
        Lbl4.setText("Veggie Galore Pizza");
        getContentPane().add(Lbl4);
        Lbl4.setBounds(460, 590, 180, 30);

        Lbl5.setAlignment(java.awt.Label.CENTER);
        Lbl5.setBackground(new java.awt.Color(0, 204, 204));
        Lbl5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Lbl5.setForeground(new java.awt.Color(255, 255, 255));
        Lbl5.setText("Cheese Deluxe Pizza");
        getContentPane().add(Lbl5);
        Lbl5.setBounds(780, 590, 180, 30);

        Lbl6.setAlignment(java.awt.Label.CENTER);
        Lbl6.setBackground(new java.awt.Color(0, 204, 204));
        Lbl6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Lbl6.setForeground(new java.awt.Color(255, 255, 255));
        Lbl6.setText("Mix Sensation Pizza");
        getContentPane().add(Lbl6);
        Lbl6.setBounds(1090, 590, 180, 30);

        LblPrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblPrice.setForeground(new java.awt.Color(255, 255, 255));
        LblPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPrice.setText("PRICE");
        getContentPane().add(LblPrice);
        LblPrice.setBounds(250, 190, 60, 20);

        LblItems.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblItems.setForeground(new java.awt.Color(255, 255, 255));
        LblItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblItems.setText("ITEMS");
        getContentPane().add(LblItems);
        LblItems.setBounds(90, 190, 140, 20);

        LblNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblNo.setForeground(new java.awt.Color(255, 255, 255));
        LblNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNo.setText("PIZZA NO.");
        getContentPane().add(LblNo);
        LblNo.setBounds(30, 190, 60, 20);

        LblQuantity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        LblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblQuantity.setText("QUANTITY");
        getContentPane().add(LblQuantity);
        LblQuantity.setBounds(320, 190, 60, 20);

        LblItems3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LblItems3.setForeground(new java.awt.Color(255, 255, 0));
        LblItems3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblItems3.setText("GST (6%) AND SST (6%) INCLUDED");
        getContentPane().add(LblItems3);
        LblItems3.setBounds(160, 550, 210, 30);

        LblItems2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblItems2.setForeground(new java.awt.Color(255, 255, 255));
        LblItems2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblItems2.setText("TOTAL: ");
        getContentPane().add(LblItems2);
        LblItems2.setBounds(180, 480, 60, 30);

        LblItems1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblItems1.setForeground(new java.awt.Color(255, 255, 255));
        LblItems1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblItems1.setText("FINAL TOTAL: ");
        getContentPane().add(LblItems1);
        LblItems1.setBounds(140, 520, 100, 30);

        jPhoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1.2.jpg"))); // NOI18N
        getContentPane().add(jPhoto1);
        jPhoto1.setBounds(400, 430, 300, 180);

        jPhoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/4.1.JPG"))); // NOI18N
        getContentPane().add(jPhoto4);
        jPhoto4.setBounds(1020, 430, 300, 180);

        jPhoto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/2.2.jpg"))); // NOI18N
        getContentPane().add(jPhoto6);
        jPhoto6.setBounds(710, 430, 300, 180);

        jPhoto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/6.1.jpg"))); // NOI18N
        getContentPane().add(jPhoto8);
        jPhoto8.setBounds(1020, 160, 300, 180);

        jPhoto9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/3.1.jpg"))); // NOI18N
        getContentPane().add(jPhoto9);
        jPhoto9.setBounds(710, 160, 300, 180);

        jPhoto11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/5.1.jpg"))); // NOI18N
        getContentPane().add(jPhoto11);
        jPhoto11.setBounds(400, 160, 300, 180);

        JGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/2gif.gif"))); // NOI18N
        getContentPane().add(JGif);
        JGif.setBounds(180, 10, 160, 140);

        jTextField.setBackground(new java.awt.Color(0, 0, 0));
        jTextField.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField);
        jTextField.setBounds(20, 160, 370, 540);

        JBackground.setBackground(new java.awt.Color(255, 255, 255));
        JBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/22bckgrnd.png"))); // NOI18N
        getContentPane().add(JBackground);
        JBackground.setBounds(0, -60, 1380, 830);

        getAccessibleContext().setAccessibleName("Pizza Yum!");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy1ActionPerformed
    i=1; items="Pepperoni Pizza"; sales=26.00;
    No1.setText(""+i); Item1.setText(items); Price1.setText("RM"+ String.format("%.2f", sales));
    String qty1 = JOptionPane.showInputDialog("Quantity?", "1");
    Qty1.setText(qty1);
    //double quantity = Double.parseDouble(qty1);

    }//GEN-LAST:event_btnBuy1ActionPerformed

    private void btnBuy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy2ActionPerformed
       i=2; items="Aloha Pizza"; sales=26.00;

        No2.setText(""+i); Item2.setText(items); Price2.setText("RM"+ String.format("%.2f", sales));
        String qty2 = JOptionPane.showInputDialog("Quantity?", "1");
        Qty2.setText(qty2);
        //double quantity = Double.parseDouble(qty2);

    }//GEN-LAST:event_btnBuy2ActionPerformed

    private void btnBuy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy3ActionPerformed
        i=3; items="Meaty Mushroom Pizza"; sales=28.00;

        No3.setText(""+i); Item3.setText(items); Price3.setText("RM"+ String.format("%.2f", sales));
        String qty3 = JOptionPane.showInputDialog("Quantity?", "1");
        Qty3.setText(qty3);

    }//GEN-LAST:event_btnBuy3ActionPerformed

    private void btnBuy4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy4ActionPerformed
         i=4; items="Veggie Galore Pizza"; sales=28.00;

        No4.setText(""+i); Item4.setText(items); Price4.setText("RM"+ String.format("%.2f", sales));
        String qty4 = JOptionPane.showInputDialog("Quantity?", "1");
        Qty4.setText(qty4);

    }//GEN-LAST:event_btnBuy4ActionPerformed

    private void btnBuy5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy5ActionPerformed
        i=5; items="Cheese Deluxe Pizza"; sales=25.00;

        No5.setText(""+i); Item5.setText(items); Price5.setText("RM"+ String.format("%.2f", sales));
        String qty5 = JOptionPane.showInputDialog("Quantity?", "1");
        Qty5.setText(qty5);

    }//GEN-LAST:event_btnBuy5ActionPerformed

    private void btnBuy6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuy6ActionPerformed
        i=6; items="Mix Sensation Pizza"; sales=28.00;

        No6.setText(""+i); Item6.setText(items); Price6.setText("RM"+ String.format("%.2f", sales));
        String qty6 = JOptionPane.showInputDialog("Quantity?", "1");
        Qty6.setText(qty6);
        
    }//GEN-LAST:event_btnBuy6ActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed

    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed

        JOptionPane.showMessageDialog(null, "Your receipt is printing...\n\n\n\n\n"
                + "Receipt has been printed out.\n\nThank you for buying in PIZZA YUM.\n Have a nice day!", "Receipt",
            JOptionPane.INFORMATION_MESSAGE); 

    }//GEN-LAST:event_btnReceiptActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        total2=0; total1=0; sales=0; quantity=0; i=0; 
        totalPizza1=0.0; totalPizza2=0.0; totalPizza3=0.0; totalPizza4=0.0; totalPizza5=0.0; totalPizza6=0.0;
        ItemFinalTotal.setText(""); ItemTotal.setText("");
        No1.setText(""); No2.setText(""); No3.setText(""); No4.setText(""); No5.setText(""); No6.setText("");
        Item1.setText(""); Item2.setText(""); Item3.setText(""); Item4.setText(""); Item5.setText(""); Item6.setText("");
        Price1.setText(""); Price2.setText(""); Price3.setText(""); Price4.setText(""); Price5.setText(""); Price6.setText("");
        Qty1.setText("0"); Qty2.setText("0"); Qty3.setText("0"); Qty4.setText("0"); Qty5.setText("0"); Qty6.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
     
        double q1 = Double.parseDouble(Qty1.getText());
        double q2 = Double.parseDouble(Qty2.getText());
        double q3 = Double.parseDouble(Qty3.getText());
        double q4 = Double.parseDouble(Qty4.getText());
        double q5 = Double.parseDouble(Qty5.getText());
        double q6 = Double.parseDouble(Qty6.getText());    
        
        totalPizza1 = price[1] * q1;
        totalPizza2 = price[1] * q2;
        totalPizza3 = price[2] * q3;
        totalPizza4 = price[2] * q4;
        totalPizza5 = price[0] * q5;
        totalPizza6 = price[2] * q6;
      
        //Calculate Grand Total of Order BEFORE Tax
        total1 = totalPizza1 + totalPizza2 + totalPizza3 + totalPizza4 + totalPizza5 + totalPizza6;
        //Calculate Grand Total of Order AFTER Tax
        total2 = total1 + (total1 * tax);
        //Display Grand Total
        calc(total2, total1);
    }//GEN-LAST:event_btnTotalActionPerformed

    private void ItemFinalTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemFinalTotalActionPerformed

    }//GEN-LAST:event_ItemFinalTotalActionPerformed

    private void ItemTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemTotalActionPerformed

    }//GEN-LAST:event_ItemTotalActionPerformed

    private void No1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_No1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_No1MouseClicked

    private void No1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No1ActionPerformed

    }//GEN-LAST:event_No1ActionPerformed

    private void Item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item1ActionPerformed

    private void Price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price1ActionPerformed

    private void Qty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qty1ActionPerformed

    private void No3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_No3ActionPerformed

    private void Qty4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qty4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qty4ActionPerformed

    private void Price5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price5ActionPerformed

    private void No6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_No6ActionPerformed

    private void Item6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item6ActionPerformed

    private void Price6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price6ActionPerformed

    private void Qty6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qty6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qty6ActionPerformed

    private void Qty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qty2ActionPerformed

    private void Qty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qty3ActionPerformed

        private void calc(double total2, double total1)
    {
        ItemTotal.setText("RM"+String.format("%.2f", total1));
        ItemFinalTotal.setText("RM"+String.format("%.2f", total2));
        
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pizza().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Item1;
    private javax.swing.JTextField Item2;
    private javax.swing.JTextField Item3;
    private javax.swing.JTextField Item4;
    private javax.swing.JTextField Item5;
    private javax.swing.JTextField Item6;
    private javax.swing.JTextField ItemFinalTotal;
    private javax.swing.JTextField ItemTotal;
    private javax.swing.JLabel JBackground;
    private javax.swing.JLabel JGif;
    private java.awt.Label Lbl1;
    private java.awt.Label Lbl2;
    private java.awt.Label Lbl3;
    private java.awt.Label Lbl4;
    private java.awt.Label Lbl5;
    private java.awt.Label Lbl6;
    private javax.swing.JLabel LblItems;
    private javax.swing.JLabel LblItems1;
    private javax.swing.JLabel LblItems2;
    private javax.swing.JLabel LblItems3;
    private javax.swing.JLabel LblNo;
    private javax.swing.JLabel LblPrice;
    private javax.swing.JLabel LblQuantity;
    private javax.swing.JTextField No1;
    private javax.swing.JTextField No2;
    private javax.swing.JTextField No3;
    private javax.swing.JTextField No4;
    private javax.swing.JTextField No5;
    private javax.swing.JTextField No6;
    private javax.swing.JTextField Price1;
    private javax.swing.JTextField Price2;
    private javax.swing.JTextField Price3;
    private javax.swing.JTextField Price4;
    private javax.swing.JTextField Price5;
    private javax.swing.JTextField Price6;
    private javax.swing.JTextField Qty1;
    private javax.swing.JTextField Qty2;
    private javax.swing.JTextField Qty3;
    private javax.swing.JTextField Qty4;
    private javax.swing.JTextField Qty5;
    private javax.swing.JTextField Qty6;
    private java.awt.Button btnBuy1;
    private java.awt.Button btnBuy2;
    private java.awt.Button btnBuy3;
    private java.awt.Button btnBuy4;
    private java.awt.Button btnBuy5;
    private java.awt.Button btnBuy6;
    private java.awt.Button btnClear;
    private java.awt.Button btnReceipt;
    private java.awt.Button btnTotal;
    private javax.swing.JLabel jPhoto1;
    private javax.swing.JLabel jPhoto11;
    private javax.swing.JLabel jPhoto4;
    private javax.swing.JLabel jPhoto6;
    private javax.swing.JLabel jPhoto8;
    private javax.swing.JLabel jPhoto9;
    private javax.swing.JTextField jTextField;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
